# Generated by Django 6.0.7 on 2026-08-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(help_text='Short summary shown on cards and as the article lead.')),
                ('description', models.TextField(help_text='Article body. Separate paragraphs with a blank line.')),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, default='Studio', help_text='Label above the card, e.g. Brand Strategy.', max_length=80)),
                ('image', models.ImageField(blank=True, help_text='Cover image (upload).', upload_to='blogs/')),
                ('image_url', models.URLField(blank=True, help_text='Or an external cover image URL (used when no upload).')),
                ('read_time', models.CharField(blank=True, default='5 min read', max_length=40)),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='hello@vanguard.studio', max_length=254)),
            ],
            options={
                'verbose_name': 'Footer settings',
                'verbose_name_plural': 'Footer settings',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Footer office',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in the gallery.')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(help_text='Client / big name, e.g. NETFLIX', max_length=120)),
                ('subtitle', models.CharField(help_text='Project name, e.g. STRANGER THINGS EXPERIENCE', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Case-study copy shown in the project detail overlay.')),
                ('date', models.DateField(help_text='Project date — the year shows in the gallery.')),
                ('external_url', models.URLField(blank=True, help_text='External URL for the “Visit live site” button. Leave empty to hide it.', verbose_name='Visit full site link')),
            ],
            options={
                'ordering': ['order', '-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order. The first 4 show on the homepage.')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Service name')),
                ('description', models.TextField(help_text='Short card text shown on the stack card and services grid.')),
                ('summary', models.TextField(blank=True, help_text='Longer intro on the service page. Falls back to the description if empty.')),
                ('what_we_define_heading', models.CharField(default='What we define', help_text='e.g. What we define / What we design / What we build.', max_length=80, verbose_name='First section heading')),
                ('what_we_define', models.TextField(blank=True, help_text='First section on the service page.', verbose_name='What we define')),
                ('how_we_work', models.TextField(blank=True, help_text='Second section on the service page.', verbose_name='How we work')),
                ('leave_with', models.TextField(blank=True, help_text='Outcomes list — one item per line.', verbose_name='What you leave with')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated chips, e.g. Research, Positioning, Naming', max_length=250)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Footer social link',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0, help_text='0 = cover (gallery card + first detail image).')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Tags — pick from your services.', related_name='projects', to='content.service'),
        ),
    ]
